event-api.check-connection:
  path: /connection
  methods: [GET]
  controller: App\Controllers\Connection\ConnectionController
  method: check

event-api.register.examples-keys:
  path: /register/examples-keys
  methods: [GET]
  controller: App\Controllers\Connection\ConnectionController
  method: exampleJWT