event-api.check-connection:
  path: /connection
  methods: [GET]
  controller: App\Controllers\Connection\ConnectionController
  method: check

event-api.examples-token:
  path: /getExampleToken
  methods: [GET]
  controller: App\Controllers\Connection\ConnectionController
  method: exampleJWT

event-api.get-entity:
  path: /{entity}
  methods: [POST]
  controller: App\Controllers\EntityManagerController\EntityManagerController
  method: entity
  params:
    entity: [user, capteur, forum, forum_message, organization, reservation, room, status]