event-api.check-connection:
  path: /connection
  request_methods: [GET]
  controller: App\Controllers\Connection\ConnectionController
  method: check

event-api.examples-token:
  path: /getExampleToken
  request_methods: [GET]
  controller: App\Controllers\Connection\ConnectionController
  method: exampleJWT

event-api.get-entity:
  path: /{entity}
  request_methods: [GET]
  controller: App\Controllers\EntityManagerController\EntityManagerController
  method: getEntity
  params:
    entity: [user, capteur, forum, forum_message, organization, reservation, room]

event-api.create-entity:
  path: /{entity}
  request_methods: [POST]
  controller: App\Controllers\EntityManagerController\EntityManagerController
  method: createEntity
  params:
    entity: [user, capteur, forum, forum_message, organization, reservation, room]