event-api.check-connection:
  path: /connection
  methods: [GET]
  controller: App\Controllers\Connection\ConnectionController
  method: check

event-api.examples-token:
  path: /getExampleToken
  methods: [GET]
  controller: App\Controllers\Connection\ConnectionController
  method: exampleJWT