openapi: 3.0.0
info:
  title: Event-API
  description: 'API for event event-it web site'
  contact:
    name: G8D
  version: '1.0'
servers:
  -
    url: 'https://localhost:8000'
    description: 'development server'
paths:
  /connection:
    get:
      operationId: 514b3b673317c6cf5fc891702d38d11e
      responses:
        '200':
          description: 'Check if the connection is working.'
          content:
            application/json:
              schema:
                description: 'Connection status'
                type: boolean
  /getExampleToken:
    get:
      operationId: b2b182d9d78c244d14bd3738609a6132
      responses:
        '200':
          description: 'Generate public and private keys for JWT authentication'
          content:
            application/json:
              schema:
                description: 'Connection status'
                type: string
