openapi: 3.0.0
info:
  title: Connection API
  version: 1.0.0
  description: API for checking connection status
paths:
  /connection:
    get:
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  connection:
                    type: boolean
                    description: Indicates whether the connection is okay or not.
                    example: true