openapi: 3.0.0
info:
  title: Event-API
  description: 'API for event event-it web site'
  contact:
    name: G8D
  version: '1.0'
servers:
  -
    url: 'https://localhost:8000'
    description: 'development server'
paths:
  /connection:
    get:
      operationId: 514b3b673317c6cf5fc891702d38d11e
      responses:
        '200':
          description: 'Check if the connection is working.'
          content:
            application/json:
              schema:
                description: 'Connection status'
                type: boolean
  /getExampleToken:
    get:
      operationId: b2b182d9d78c244d14bd3738609a6132
      responses:
        '200':
          description: 'Generate public and private keys for JWT authentication'
          content:
            application/json:
              schema:
                description: 'Connection status'
                type: string
  /login:
    post:
      operationId: 395dbc7a2086577e6e0658161be85ce6
      requestBody:
        content:
          application/json:
            schema:
              properties:
                email:
                  type: string
                password:
                  type: string
              type: object
      responses:
        '200':
          description: 'Login to the API'
          headers:
            Access-Control-Allow-Origin:
              description: 'CORS header'
              schema:
                type: string
            Access-Control-Allow-Methods:
              description: 'CORS header'
              schema:
                type: string
            Access-Control-Allow-Headers:
              description: 'CORS header'
              schema:
                type: string
    options:
      operationId: c23e7d7bf7816ee6c0e1232b1b422689
      responses:
        '200':
          description: 'Preflight response'
          headers:
            Access-Control-Allow-Origin:
              description: 'CORS header'
              schema:
                type: string
            Access-Control-Allow-Methods:
              description: 'CORS header'
              schema:
                type: string
            Access-Control-Allow-Headers:
              description: 'CORS header'
              schema:
                type: string
  '/{entity}':
    get:
      operationId: 3bef539a9a6bfbc257e47b3b9189fa97
      parameters:
        -
          name: entity
          in: path
          description: 'Entity name'
          required: true
          schema:
            type: string
            enum:
              - user
              - capteur
              - CapteurArchive
              - forum
              - ForumMessage
              - organization
              - reservation
              - room
              - status
      responses:
        '200':
          description: 'Request an entity to the API'
    post:
      operationId: a0d7eebea0354cbea18436f2390c3d8a
      parameters:
        -
          name: entity
          in: path
          description: 'Entity name'
          required: true
          schema:
            type: string
            enum:
              - user
              - capteur
              - CapteurArchive
              - forum
              - ForumMessage
              - organization
              - reservation
              - room
              - status
      responses:
        '200':
          description: 'Create the entity'
components:
  responses:
    '200':
      description: 'Update the entity'
  parameters:
    entity:
      name: entity
      in: path
      description: 'Entity name'
      required: true
      schema:
        type: string
        enum:
          - user
          - capteur
          - CapteurArchive
          - forum
          - ForumMessage
          - organization
          - reservation
          - room
          - status
