openapi: 3.0.0
info:
  title: Event-API
  description: 'API for event event-it web site'
  contact:
    name: G8D
  version: '1.0'
servers:
  -
    url: 'https://localhost:8000'
    description: 'development server'
paths:
  /connection:
    get:
      operationId: 514b3b673317c6cf5fc891702d38d11e
      responses:
        '200':
          description: 'Check if the connection is working.'
          content:
            application/json:
              schema:
                description: 'Connection status'
                type: boolean
  /getExampleToken:
    get:
      operationId: b2b182d9d78c244d14bd3738609a6132
      responses:
        '200':
          description: 'Generate public and private keys for JWT authentication'
          content:
            application/json:
              schema:
                description: 'Connection status'
                type: string
  /login:
    post:
      tags:
        - Login
      summary: 'Log in a user'
      operationId: loginUser
      requestBody:
        description: 'User credentials'
        required: true
        content:
          application/json:
            schema:
              required:
                - email
                - password
              properties:
                email:
                  type: string
                  example: user@example.com
                password:
                  type: string
                  example: yourpassword
              type: object
      responses:
        '200':
          description: 'Successful login'
          content:
            application/json:
              schema:
                properties:
                  token: { description: 'Authentication token', type: string }
                type: object
        '400':
          description: 'Invalid credentials'
  '/{entity}':
    get:
      operationId: 3bef539a9a6bfbc257e47b3b9189fa97
      parameters:
        -
          name: entity
          in: path
          description: 'Entity name'
          required: true
          schema:
            type: string
            enum:
              - user
              - capteur
              - CapteurArchive
              - forum
              - ForumMessage
              - organization
              - reservation
              - room
              - status
              - currentUser
              - faq
      responses:
        '200':
          description: 'Request an entity to the API'
    post:
      operationId: a0d7eebea0354cbea18436f2390c3d8a
      parameters:
        -
          name: entity
          in: path
          description: 'Entity name'
          required: true
          schema:
            type: string
            enum:
              - user
              - capteur
              - CapteurArchive
              - forum
              - ForumMessage
              - organization
              - reservation
              - room
              - status
              - faq
      responses:
        '200':
          description: 'Create the entity'
    patch:
      operationId: 138550b22631dd6f66c1fcff825963e8
      parameters:
        -
          name: entity
          in: path
          description: 'Entity name'
          required: true
          schema:
            type: string
            enum:
              - user
              - capteur
              - CapteurArchive
              - forum
              - ForumMessage
              - organization
              - reservation
              - room
              - status
              - faq
      responses:
        '200':
          description: 'Create the entity'
components:
  responses:
    '200':
      description: 'Get the current user'
      content:
        application/json:
          schema:
            description: 'User object'
            type: object
