version: '3.8'

services:
  php:
    build: 
      context: .
      dockerfile: Dockerfile
    image: php:8.2-apache
    container_name: php-8.2-apache
    ports:
      - "9000:80"
    volumes:
      - ./src:/var/www/html